max_sections = [2000]
fault_model=["CFM_1_0_DOM_SANSTVZ"]
max_jump_distance=[ 15, ]
adaptive_min_distance=[ 6, ]
thinning_factor=[ 0, ]
min_sub_sects_per_parent=[2]
min_sub_sections=[2]
sans = 0.8
title = "Build Coulomb CFM 1.0 sans with regional depth scaling"
description = "used to test effect of code change to Coulomb builder against older rupture sets that use CFM_1_0_DOM_SANSTVZ"


[[depth_scaling]]
tvz = 0.667