site_name: Runzi Documentation
site_url: https://gns-science.github.io/nzshm-runzi
repo_url: https://github.com/GNS-Science/nzshm-runzi
repo_name: GNS-Science/nzshm-runzi
# strict: true
watch:
  - runzi
  - docs
nav:
  - Home: index.md
  - Usage:
    - CLI: usage/cli.md
    - Environment Variables: usage/environment_variables.md
    - Hazard: usage/hazard.md
    - Docker: usage/docker/docker.md
    - Inversion, Docker, and AWS: usage/docker/AWS_docker_containers_setup.md
  - Installation: installation.md
  - Development and Contributing:
    - contributing.md
    - Testing: testing.md
  - Changelog: changelog.md

theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - tables

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_if_no_docstring: true
            signature_crossrefs: true
            annotations_path: source
            merge_init_into_class: true
            group_by_category: true
            show_category_heading: true
            members_order: source
            inherited_members: false

          extensions:
          - pydantic: {schema: true}

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GNS-Science/nzshm-runzi
      name: GitHub
    - icon: material/email
      link: "mailto:nshm@gns.cri.nz"