[tool.poetry]
name = "nzshm-runzi"
version = "0.2.2"
description = "scripting and cli for the NSHM"
authors = ["GNS NSHM programme"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    {include = "runzi"},
    {include = "scripts"}
]

[tool.poetry.scripts]
runzi = 'scripts.cli:rnz'

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
gitpython = "3.1.11"
gql = "^3.2.0"
py4j = "0.10.9.1"
python-dateutil = "2.8.1"
pytz = "^2022.7"
nshm-toshi-client = ">=1.0.0"
prompt-toolkit = "3.0.20"
termcolor = "1.1.0"
inquirer = "2.7.0"
pygments = "2.10.0"
pyfiglet = "0.8.post1"
boto3 = "^1.26.43"
requests-toolbelt = "^0.10.1"
lxml = "^4.9.2"
requests = "2.27.1"
tqdm = "^4.65.0"
openquake-engine = {path = "../CALCULATION/oq-engine", optional = true, develop = true}
openquake-converters-ucerf = {path = "../COMPONENTS/ucerf", optional = true, develop = true}
toshi-hazard-store = "^0.7.5"
toml = "^0.10.2"
click = "^8.1.7"
nzshm-model = "^0.4.0"
nzshm-common = {extras = ["geometry"], version = "^0.6.0"}

[tool.poetry.extras]
openquake = ["openquake-engine"]
converter =["openquake-converters-ucerf"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
