[project]
name = "nzshm-runzi"
version = "0.1.0"
readme = "README.md"
authors = [
    {name = "Chris DiCaprio", email = "christopher.dicaprio@gmail.com"}, 
    {name = "Chris Chamberlain", email = "chrisbc@artisan.co.nz"}, 
    {name = "Oakley Jurgens", email = "oakley.jurgens@gns.cri.nz"}, 
]
description = "scripting and cli for the NSHM"
license = "GPL-3.0-only"
requires-python = ">=3.10,<3.12"
dependencies = [
    "gitpython (>=3.1.11)",
    "py4j (==0.10.9.1)",
    "nshm-toshi-client (>=1.0.0)",
    "prompt-toolkit (==3.0.20)",
    "termcolor (>=1.1.0)",
    "pyfiglet (>=0.8.post1)",
    "boto3 (>=1.26.43)",
    "lxml (>=4.9.2)",
    "tqdm (>=4.65.0)",
    "click (>=8.1.7)",
    "python-dateutil (>=2.8.2)",
    "nzshm-common[geometry] (>=0.8.4)",
    "inquirer (>=3.4.0)",
    "pygments (>=2.19.1)",
    "pytz (>=2025.1)",
    "pydantic (>=2.10.6)",
    "tomlkit (>=0.13.2)",
    "solvis (>=1.0.0)",
    "nzshm-model (>=0.13.6)",
    "python-dotenv (>=1.1.0)",
    "toshi-hazard-store (>=1.0.0)",
    "ariadne-codegen (>=0.14.0,<0.15.0)",
]


[tool.poetry]
packages = [
    {include = "runzi"},
]


[tool.poetry.scripts]
runzi-hazard = 'runzi.automation.cli:rnz_hazard'


[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.4"
flake8 = ">=7.1.1"
black = ">=25.1.0"
isort = ">=6.0.0"
bump2version = "^1.0.1"
tox = "^4.24.1"
mypy = "^1.14.1"
pytest-cov = "^6.0.0"
types-requests = "^2.32.0.20241016"
types-pytz = "^2025.1.0.20250204"
types-python-dateutil = "^2.9.0.20241206"
types-toml = ">=0.10.8.20240310"
pytest-mock = "^3.14.0"
vulture = "^2.14"


[tool.poetry.group.doc.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.50"
mkdocs-click = ">=0.8.1"
mkdocs-include-markdown-plugin = "^7.1.2"
mkdocstrings = ">=0.27.0"


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py312', 'py311', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | runzi/CONFIG
)/
'''

[tool.mypy]
ignore_missing_imports = true
exclude = [
    'runzi/CONFIG',
    'runzi/automation/arkiv',
    'runzi/automation/openquake/run_oq_disagg.py',
]

[tool.ariadne-codegen]
schema_path = "runzi/automation/scaling/toshi_api_codegen/schema.graphql"
queries_path = "runzi/automation/scaling/toshi_api_codegen/queries.graphql"
enable_custom_operations = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

