[tool.poetry]
name = "nzshm-runzi"
version = "0.2.2"
description = "scripting and cli for the NSHM"
authors = ["GNS NSHM programme"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [{include = "runzi"}]

[tool.poetry.dependencies]
python = "^3.8"
gitpython = "3.1.11"
gql = "^3.2.0"
py4j = "0.10.9.1"
python-dateutil = "2.8.1"
pytz = "^2022.7"
nshm-toshi-client = ">=1.0.0"
prompt-toolkit = "3.0.20"
termcolor = "1.1.0"
inquirer = "2.7.0"
pygments = "2.10.0"
pyfiglet = "0.8.post1"
boto3 = "^1.26.43"
requests-toolbelt = "^0.10.1"
lxml = "^4.9.2"
requests = "2.27.1"
pytest = "^7.2.0"
nzshm-common = {git = "https://github.com/GNS-Science/nzshm-common-py.git", rev = "feature/20-backarc-v2", extras = ["geometry"]}
toshi-hazard-store = {git = "https://github.com/GNS-Science/toshi-hazard-store.git", rev = "fix/multi_batch"}
openquake-engine = {git = "https://github.com/chrisdicaprio/oq-engine.git", rev = "feature/disagg_bin_edges", optional = true}
openquake-converters-ucerf = {path = "/home/chrisdc/NSHM/DEV/COMPONENTS/ucerf", optional = true, develop = true}
tqdm = "^4.65.0"

[tool.poetry.extras]
openquake = ["openquake-engine"]
converter =["openquake-converters-ucerf"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
