[tool.poetry]
name = "nzshm-runzi"
version = "0.2.2"
description = "scripting and cli for the NSHM"
authors = ["GNS NSHM programme"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    {include = "runzi"},
    {include = "scripts"}
]

[tool.poetry.scripts]
runzi = 'scripts.cli:rnz'

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
gitpython = "3.1.11"
py4j = "0.10.9.1"
pytz = "^2022.7"
nshm-toshi-client = ">=1.0.0"
prompt-toolkit = "3.0.20"
termcolor = "1.1.0"
inquirer = "2.7.0"
pygments = "2.10.0"
pyfiglet = "0.8.post1"
boto3 = "^1.26.43"
lxml = "^4.9.2"
tqdm = "^4.65.0"
toml = "^0.10.2"
click = "^8.1.7"
python-dateutil = "^2.8.2"

# [tool.poetry.extras]
# openquake = ["openquake-engine", "fiona"]
# converter =["openquake-converters-ucerf"]
nzshm-common = {extras = ["geometry"], version = "^0.6.1"}
toshi-hazard-store = "^0.7.9"
nzshm-model = "0.10.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
flake8 = "^6.1.0"
black = "^23.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
