# Generated by ariadne-codegen
# Source: runzi/automation/scaling/toshi_api_codegen/queries.graphql

from typing import Optional

from .base_model import BaseModel


class CreateGeneralTask(BaseModel):
    create_general_task: Optional["CreateGeneralTaskCreateGeneralTask"]


class CreateGeneralTaskCreateGeneralTask(BaseModel):
    general_task: Optional["CreateGeneralTaskCreateGeneralTaskGeneralTask"]


class CreateGeneralTaskCreateGeneralTaskGeneralTask(BaseModel):
    id: str


CreateGeneralTask.model_rebuild()
CreateGeneralTaskCreateGeneralTask.model_rebuild()
