# Generated by ariadne-codegen
# Source: runzi/automation/scaling/toshi_api_codegen/schema.graphql

from enum import Enum


class AggregationFn(str, Enum):
    MEAN = "MEAN"


class EventResult(str, Enum):
    FAILURE = "FAILURE"
    PARTIAL = "PARTIAL"
    SUCCESS = "SUCCESS"
    UNDEFINED = "UNDEFINED"


class EventState(str, Enum):
    SCHEDULED = "SCHEDULED"
    STARTED = "STARTED"
    DONE = "DONE"
    UNDEFINED = "UNDEFINED"


class FileRole(str, Enum):
    READ = "READ"
    WRITE = "WRITE"
    READ_WRITE = "READ_WRITE"
    UNDEFINED = "UNDEFINED"


class ModelType(str, Enum):
    CRUSTAL = "CRUSTAL"
    SUBDUCTION = "SUBDUCTION"
    COMPOSITE = "COMPOSITE"


class OpenquakeTaskType(str, Enum):
    HAZARD = "HAZARD"
    DISAGG = "DISAGG"
    UNDEFINED = "UNDEFINED"


class RowItemType(str, Enum):
    integer = "integer"
    double = "double"
    string = "string"
    boolean = "boolean"


class SmsFileType(str, Enum):
    BH = "BH"
    CPT = "CPT"
    DH = "DH"
    HVSR = "HVSR"
    SW = "SW"


class SmsSiteClass(str, Enum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"


class SmsSiteClassBasis(str, Enum):
    Vs = "Vs"
    SPT = "SPT"
    su = "su"


class TableType(str, Enum):
    HAZARD_GRIDDED = "HAZARD_GRIDDED"
    HAZARD_SITES = "HAZARD_SITES"
    MFD_CURVES = "MFD_CURVES"
    MFD_CURVES_V2 = "MFD_CURVES_V2"
    GENERAL = "GENERAL"


class TaskSubType(str, Enum):
    RUPTURE_SET = "RUPTURE_SET"
    INVERSION = "INVERSION"
    HAZARD = "HAZARD"
    REPORT = "REPORT"
    SCALE_SOLUTION = "SCALE_SOLUTION"
    AGGREGATE_SOLUTION = "AGGREGATE_SOLUTION"
    SOLUTION_TO_NRML = "SOLUTION_TO_NRML"
    OPENQUAKE_HAZARD = "OPENQUAKE_HAZARD"
    TIME_DEPENDENT_SOLUTION = "TIME_DEPENDENT_SOLUTION"
