# Generated by ariadne-codegen
# Source: runzi/automation/scaling/toshi_api_codegen/queries.graphql

from typing import Optional

from .base_model import BaseModel


class UpdateSubtaskCount(BaseModel):
    update_general_task: Optional["UpdateSubtaskCountUpdateGeneralTask"]


class UpdateSubtaskCountUpdateGeneralTask(BaseModel):
    ok: Optional[bool]


UpdateSubtaskCount.model_rebuild()
