# Example of .toml configuration file. Copy and paste into a text file the
# lines below.
# The .toml synthax is described here: https://github.com/toml-lang/toml

# Options for the `type` parameter: 'geojson' or 'bin'
type = 'geojson'
source_id = 'SW52ZXJzaW9uU29sdXRpb246MTU2NjcuMHpxc1dM' #SW52ZXJzaW9uU29sdXRpb246MTU2NjcuMHpxc1dM
source_name = 'nzshm-opensha Crustal demo'
# Unit of measure for the rupture sampling: km
rupture_sampling_distance = 1
# The `tectonic_region_type` label must be consistent with what you use in the
# logic tree for the ground-motion characterisation
# Use "Subduction Interface" or "Active Shallow Crust"
tectonic_region_type = "Active Shallow Crust"
# Unit of measure for the `investigation_time`: years
investigation_time = 1.0