"""Block until the JVM's py4j gateway is accepting connections, then exit.

Both Java-task launchers run this before starting the Python client:

- the LOCAL/CLUSTER bash generated by ``OpenshaTaskFactory``, and
- the AWS Batch container entrypoint ``docker/java_container_task.sh``

as ``python3 -m runzi.automation.wait_for_gateway <port> <pid>``. py4j does a single, non-retrying
``connect()`` on the client's first call, so starting the client before the JVM binds its port fails
the whole task with ``ConnectionRefusedError`` (worst on a cold JVM/disk cache; e.g. coulomb connects
in its ``__init__``). Keeping the wait here means the two launchers share one implementation instead
of each embedding a hand-copied ``python3 -c`` poll that can drift.

Exit code: 0 once the port is connectable; 1 if the gateway process (``pid``) exits before binding the
port, or if the timeout elapses first.
"""

from __future__ import annotations

import os
import socket
import sys
import time

DEFAULT_TIMEOUT_S = 60.0
_POLL_INTERVAL_S = 0.2
_CONNECT_TIMEOUT_S = 0.5


def _process_alive(pid: int | None) -> bool:
    """True if ``pid`` is still running (or if liveness can't be probed cheaply here).

    Uses the POSIX ``kill(pid, 0)`` probe. The launchers that invoke this module are Unix-only; on
    Windows ``os.kill(pid, 0)`` is not a liveness check (signal 0 is ``CTRL_C_EVENT`` there), so we
    skip the early exit and let the timeout bound the wait instead.
    """
    if pid is None or sys.platform == "win32":
        return True
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def wait_for_gateway(port: int, pid: int | None = None, timeout: float = DEFAULT_TIMEOUT_S) -> bool:
    """Poll ``127.0.0.1:port`` until it accepts a connection.

    Args:
        port: the py4j gateway port to poll.
        pid: the gateway JVM process id; if given, stop early when it exits before binding the port.
        timeout: give up after this many seconds.

    Returns:
        True once the port is connectable; False if ``pid`` exits first or the timeout elapses.
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with socket.socket() as s:
            s.settimeout(_CONNECT_TIMEOUT_S)
            if s.connect_ex(("127.0.0.1", port)) == 0:
                return True
        if not _process_alive(pid):
            return False
        time.sleep(_POLL_INTERVAL_S)
    return False


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not args:
        print("usage: python -m runzi.automation.wait_for_gateway <port> [pid]", file=sys.stderr)
        return 2
    port = int(args[0])
    pid = int(args[1]) if len(args) > 1 and args[1] else None
    if wait_for_gateway(port, pid):
        return 0
    if pid is not None and not _process_alive(pid):
        print(f"gateway JVM (pid {pid}) exited before binding port {port}", file=sys.stderr)
    else:
        print(f"timed out waiting for gateway JVM on port {port}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
