[general]
title = "OpenQuake Disaggregation Calcs"
description = "Disaggregation demo"

[hazard_model]
nshm_model_version = "NSHM_v1.0.4"

# these entries will overwrite anything in the nshm_model_version.
# all 3 are required if a nshm_model_version is not specified
# gmcm_logic_tree = "gmcm_small.json"
# srm_logic_tree = "srm_small.json"
# hazard_config = "hazard_config.json"


[hazard_curve]
# this is the model in toshi-hazard-store that will be used to find the target shaking level for the desired PoE
hazard_model_id = "NSHM_v1.0.4"
aggs = "mean"
# imts = ["PGA", "SA(1.5)"]
imts = "PGA"

[site_params]
vs30s = 750
locations = ["WLG", "AKL"]

[disagg]
inv_time = 50
# poes = [0.02, 0.05, 0.10, 0.18, 0.39, 0.63, 0.86]
poes = 0.02
disagg_bin_edges = {"dist" = [0, 5.0, 10.0, 15.0, 20.0, 30.0, 40.0, 50.0, 60.0, 80.0, 100.0, 140.0, 180.0, 220.0, 260.0, 320.0, 380.0, 500.0]}
mag_bin_width=0.1999
coordinate_bin_width=5
num_epsilon_bins=16
disagg_outputs = ["TRT", "Mag", "Dist", "Mag_Dist", "TRT_Mag_Dist_Eps"]

[calculation]
num_workers = 1

[output]
gt_filename = "gtids_NZplus1_allIMT_allpoe_750.txt"