[general]
title = "OpenQuake Disaggregation Calcs"
description = "Disaggregation demo"

[model]
nshm_model_version = "NSHM_v1.0.4"

# these entries will overwrite anything in the nshm_model_version.
# all 3 are required if a nshm_model_version is not specified
# gmcm_logic_tree = "gmcm_small.json"
# srm_logic_tree = "srm_small.json"
# hazard_config = "hazard_config.json"


[hazard_curve]
# this is the model in toshi-hazard-store that will be used to find the target shaking level for the desired PoE
hazard_model_id = "NSHM_v1.0.4"
agg = "mean"
imts = ["PGA", "SA(1.5)"]

[site_params]
vs30 = 750
locations = ["WLG", "AKL"]

[disagg]
inv_time = 50
poes = [0.02, 0.05, 0.10, 0.18, 0.39, 0.63, 0.86]

[calculation]
num_workers = 1

[output]
gt_filename = "gtids_NZplus1_allIMT_allpoe_750.txt"