[general]
title = "OpenQuake Hazard Calcs"
description = "Logic Tree 9.0.1, locations for cave locations"

[model]
# nshm_model_version = "NSHM_v1.0.4"
gmcm_logic_tree = "/home/chrisdc/NSHM/oqconfigs/01.05.2023/NZ_NSHM_GMM_LT_final_EE.xml"
srm_logic_tree = "/home/chrisdc/NSHM/DEV/COMPONENTS/nzshm-model/SRM_LTs/python/SLT_v9p0p0.py"

[calculation]
num_workers = 4

[hazard_curve]
imts = [
    'PGA', 'SA(0.1)', 'SA(0.2)', 'SA(0.3)', 'SA(0.4)', 'SA(0.5)', 'SA(0.7)',
    'SA(1.0)', 'SA(1.5)', 'SA(2.0)', 'SA(3.0)', 'SA(4.0)', 'SA(5.0)', 'SA(6.0)','SA(7.5)', 'SA(10.0)']
imtls = [
    0.0001, 0.0002, 0.0004, 0.0006, 0.0008,
    0.001, 0.002, 0.004, 0.006, 0.008,
    0.01, 0.02, 0.04, 0.06, 0.08,
    0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
    1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.5, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0
    ]

[site_params]
vs30 = 1000
location_list = ['WLG','AKL','DUD','CHC']

[logic_tree]
slt_decomposition = "component"

# override any of the defaults runzi uses for openquake here either for iteration or just a single value
# [openquake_iterate.general]
# ps_grid_spacing = [15, 30]

# [openquake_iterate.erf]
# rupture_mesh_spacing = [2, 4]

# [openquake_single.calculation]
# truncation_level = 3

# [openquake_single.calculation]
# maximum_distance = { "Active Shallow Crust" = "[[4.0, 0], [5.0, 100.0], [6.0, 200.0], [9.5, 250.0]]", "Subduction Interface" = "[[5.0, 0], [6.0, 200.0], [10, 600.0]]", "Subduction Intraslab" = "[[5.0, 0], [6.0, 200.0], [10, 700.0]]" }

