from .arguments import ArgSweeper
from .average_solutions_task import AverageSolutionsArgs
from .coulomb_rupture_set_builder_task import CoulombRuptureSetArgs
from .oq_opensha_convert_task import OQConvertArgs
from .scale_solution_task import ScaleSolutionArgs
from .subduction_rupture_set_builder_task import SubductionRuptureSetArgs
from .time_dependent_solution_task import TimeDependentSolutionArgs
from .inversion_diags_report_task import InversionReportArgs